#!/bin/sh
#
#
# OpenStack VPN Service (neutron-vpn-agent)
#
# Description:  Manages an OpenStack VPN Service (neutron-vpn-agent) process as an HA resource
#
# Authors:      Marcio A. Silva
# Mainly inspired by the Neutron L3 resource agent written by Emilien Macchi
#
# Support:      marcios@us.ibm.com
# License:      Apache Software License (ASL) 2.0
#
# See usage() function below for more details ...
#
# OCF instance parameters:
#   OCF_RESKEY_binary
#   OCF_RESKEY_config
#   OCF_RESKEY_l3_plugin_config
#   OCF_RESKEY_user
#   OCF_RESKEY_pid
#   OCF_RESKEY_amqp_server_port
#   OCF_RESKEY_additional_parameters
#######################################################################
# Initialization:
OCF_ROOT=${OCF_ROOT:-/usr/lib/ocf}
: ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
. ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs

#######################################################################

# Fill in some defaults if no values are specified

OCF_RESKEY_binary_default="neutron-vpn-agent"
OCF_RESKEY_config_default="/etc/neutron/neutron.conf"
OCF_RESKEY_l3_plugin_config_default="/etc/neutron/l3_agent.ini"
OCF_RESKEY_vpn_plugin_config_default="/etc/neutron/vpn_agent.ini"
OCF_RESKEY_fwaas_plugin_config_default="/etc/neutron/fwaas_agent.ini"
OCF_RESKEY_user_default="neutron"
OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
OCF_RESKEY_amqp_server_port_default="5672"

: ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
: ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
: ${OCF_RESKEY_l3_plugin_config=${OCF_RESKEY_l3_plugin_config_default}}
: ${OCF_RESKEY_vpn_plugin_config=${OCF_RESKEY_vpn_plugin_config_default}}
: ${OCF_RESKEY_fwaas_plugin_config=${OCF_RESKEY_fwaas_plugin_config_default}}
: ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
: ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
: ${OCF_RESKEY_amqp_server_port=${OCF_RESKEY_amqp_server_port_default}}

#######################################################################

usage() {
    cat <<UEND
        usage: $0 (start|stop|validate-all|meta-data|status|monitor)

        $0 manages an OpenStack VPN Service (neutron-vpn-agent) process as an HA resource 

        The 'start' operation starts the networking service.
        The 'stop' operation stops the networking service.
        The 'validate-all' operation reports whether the parameters are valid
        The 'meta-data' operation reports this RA's meta-data information
        The 'status' operation reports whether the networking service is running
        The 'monitor' operation reports whether the networking service seems to be working

UEND
}

meta_data() {
    cat <<END
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="neutron-vpn-agent">
<version>1.0</version>

<longdesc lang="en">
Resource agent for the OpenStack Neutron VPN Service (neutron-vpn-agent)
May manage a neutron-vpn-agent instance or a clone set that 
creates a distributed neutron-vpn-agent cluster.
</longdesc>
<shortdesc lang="en">Manages the OpenStack VPN Service (neutron-vpn-agent)</shortdesc>
<parameters>

<parameter name="binary" unique="0" required="0">
<longdesc lang="en">
Location of the OpenStack VPN Server server binary (neutron-vpn-agent)
</longdesc>
<shortdesc lang="en">OpenStack VPN Server server binary (neutron-vpn-agent)</shortdesc>
<content type="string" default="${OCF_RESKEY_binary_default}" />
</parameter>

<parameter name="config" unique="0" required="0">
<longdesc lang="en">
Location of the OpenStack Neutron Service (neutron-server) configuration file
</longdesc>
<shortdesc lang="en">OpenStack VPN Server (neutron-server) config file</shortdesc>
<content type="string" default="${OCF_RESKEY_config_default}" />
</parameter>

<parameter name="l3 plugin config" unique="0" required="0">
<longdesc lang="en">
Location of the OpenStack VPN Service (neutron-vpn-agent) L3 plugin configuration file
</longdesc>
<shortdesc lang="en">OpenStack VPN Server (neutron-vpn-agent) L3 plugin config file</shortdesc>
<content type="string" default="${OCF_RESKEY_l3_plugin_config_default}" />
</parameter>

<parameter name="vpn plugin config" unique="0" required="0">
<longdesc lang="en">
Location of the OpenStack VPN Service (neutron-vpn-agent) VPN plugin configuration file
</longdesc>
<shortdesc lang="en">OpenStack VPN Server (neutron-vpn-agent) VPN plugin config file</shortdesc>
<content type="string" default="${OCF_RESKEY_vpn_plugin_config_default}" />
</parameter>

<parameter name="fwaas plugin config" unique="0" required="0">
<longdesc lang="en">
Location of the OpenStack VPN Service (neutron-vpn-agent) FWAAS plugin configuration file
</longdesc>
<shortdesc lang="en">OpenStack VPN Server (neutron-vpn-agent) FWAAS plugin config file</shortdesc>
<content type="string" default="${OCF_RESKEY_fwaas_plugin_config_default}" />
</parameter>

<parameter name="user" unique="0" required="0">
<longdesc lang="en">
User running OpenStack VPN Service (neutron-vpn-agent)
</longdesc>
<shortdesc lang="en">OpenStack VPN Service (neutron-vpn-agent) user</shortdesc>
<content type="string" default="${OCF_RESKEY_user_default}" />
</parameter>

<parameter name="pid" unique="0" required="0">
<longdesc lang="en">
The pid file to use for this OpenStack VPN Service (neutron-vpn-agent) instance
</longdesc>
<shortdesc lang="en">OpenStack VPN Service (neutron-vpn-agent) pid file</shortdesc>
<content type="string" default="${OCF_RESKEY_pid_default}" />
</parameter>  

<parameter name="amqp_server_port" unique="0" required="0">                                                                                                                                                              
<longdesc lang="en">                                                                                                                                                                                                      
The listening port number of the AMQP server. Mandatory to perform a monitor check                                                                                                                                        
</longdesc>                                                                                                                                                                                                               
<shortdesc lang="en">AMQP listening port</shortdesc>                                                                                                                                                                      
<content type="integer" default="${OCF_RESKEY_amqp_server_port_default}" />                                                                                                                                              
</parameter>

<parameter name="additional_parameters" unique="0" required="0">
<longdesc lang="en">
Additional parameters to pass on to the OpenStack VPN Service (neutron-vpn-agent)
</longdesc>
<shortdesc lang="en">Additional parameters for neutron-vpn-agent</shortdesc>
<content type="string" />
</parameter>

</parameters>

<actions>
<action name="start" timeout="20" />
<action name="stop" timeout="20" />
<action name="status" timeout="20" />
<action name="monitor" timeout="30" interval="20" />
<action name="validate-all" timeout="5" />
<action name="meta-data" timeout="5" />
</actions>
</resource-agent>
END
}

#######################################################################
# Functions invoked by resource manager actions

neutron_vpn_agent_validate() {
    local rc

    check_binary $OCF_RESKEY_binary
    check_binary netstat

    # A config file on shared storage that is not available
    # during probes is OK.
    if [ ! -f $OCF_RESKEY_config ]; then
        if ! ocf_is_probe; then
            ocf_log err "Config $OCF_RESKEY_config doesn't exist"
            return $OCF_ERR_INSTALLED
        fi
        ocf_log_warn "Config $OCF_RESKEY_config not available during a probe"
    fi

    getent passwd $OCF_RESKEY_user >/dev/null 2>&1
    rc=$?
    if [ $rc -ne 0 ]; then
        ocf_log err "User $OCF_RESKEY_user doesn't exist"
        return $OCF_ERR_INSTALLED
    fi

    true
}

neutron_vpn_agent_status() {
    local pid
    local rc

    if [ ! -f $OCF_RESKEY_pid ]; then
        ocf_log info "OpenStack VPN Server (neutron-vpn-agent) is not running"
        return $OCF_NOT_RUNNING
    else
        pid=`cat $OCF_RESKEY_pid`
    fi

    ocf_run -warn kill -s 0 $pid
    rc=$?
    if [ $rc -eq 0 ]; then
        return $OCF_SUCCESS
    else
        ocf_log info "Old PID file found, but OpenStack VPN Server (neutron-vpn-agent) is not running"
        return $OCF_NOT_RUNNING
    fi
}

neutron_vpn_agent_monitor() {
    local rc
    local pid
    local network_amqp_check
    
    neutron_vpn_agent_status
    rc=$?

    # If status returned anything but success, return that immediately
    if [ $rc -ne $OCF_SUCCESS ]; then
        return $rc
    fi

    # Check the connections according to the PID.
    # We are sure to hit the vpn-agent process and not other Neutron process with the same connection behavior (for example neutron-server)
        pid=`cat $OCF_RESKEY_pid`
        # check the connections according to the PID
        network_amqp_check=`netstat -punt | grep -s "$OCF_RESKEY_amqp_server_port" | grep -s "$pid" | grep -qs "ESTABLISHED"`
        rc=$?
	    if [ $rc -ne 0 ]; then
	        ocf_log err "Neutron VPN Server is not connected to the Neutron server: $rc"
	        return $OCF_NOT_RUNNING
	    fi

    ocf_log debug "OpenStack VPN Server (neutron-vpn-agent) monitor succeeded"
    return $OCF_SUCCESS
}

neutron_vpn_agent_start() {
    local rc

    neutron_vpn_agent_status
    rc=$?
    if [ $rc -eq $OCF_SUCCESS ]; then
        ocf_log info "OpenStack VPN Server (neutron-vpn-agent) already running"
        return $OCF_SUCCESS
    fi

    # run the actual neutron-vpn-agent daemon. Don't use ocf_run as we're sending the tool's output
    # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
    su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
       --config-file=$OCF_RESKEY_vpn_plugin_config --config-file=$OCF_RESKEY_l3_plugin_config \
       --config-file=$OCF_RESKEY_fwaas_plugin_config --log-file=/var/log/neutron/vpn-agent.log $OCF_RESKEY_additional_parameters"' >> \
	/dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid

    # Spin waiting for the server to come up.
    # Let the CRM/LRM time us out if required
    while true; do
    neutron_vpn_agent_monitor
    rc=$?
    [ $rc -eq $OCF_SUCCESS ] && break
    if [ $rc -ne $OCF_NOT_RUNNING ]; then
        ocf_log err "OpenStack VPN Server (neutron-vpn-agent) start failed"
        exit $OCF_ERR_GENERIC
    fi
    sleep 1
    done

    ocf_log info "OpenStack VPN Server (neutron-vpn-agent) started"
    return $OCF_SUCCESS
}

neutron_vpn_agent_stop() {
    local rc
    local pid

    neutron_vpn_agent_status
    rc=$?
    if [ $rc -eq $OCF_NOT_RUNNING ]; then
        ocf_log info "OpenStack VPN Server (neutron-vpn-agent) already stopped"
        return $OCF_SUCCESS
    fi

    # Try SIGTERM
    pid=`cat $OCF_RESKEY_pid`
    ocf_run kill -s TERM $pid
    rc=$?
    if [ $rc -ne 0 ]; then
        ocf_log err "OpenStack VPN Server (neutron-vpn-agent) couldn't be stopped"
        exit $OCF_ERR_GENERIC
    fi

    # stop waiting
    shutdown_timeout=15
    if [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
        shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-5))
    fi
    count=0
    while [ $count -lt $shutdown_timeout ]; do
        neutron_vpn_agent_status
        rc=$?
        if [ $rc -eq $OCF_NOT_RUNNING ]; then
            break
        fi
        count=`expr $count + 1`
        sleep 1
        ocf_log debug "OpenStack VPN Server (neutron-vpn-agent) still hasn't stopped yet. Waiting ..."
    done

    neutron_vpn_agent_status
    rc=$?
    if [ $rc -ne $OCF_NOT_RUNNING ]; then
        # SIGTERM didn't help either, try SIGKILL
        ocf_log info "OpenStack VPN Server (neutron-vpn-agent) failed to stop after ${shutdown_timeout}s \
          using SIGTERM. Trying SIGKILL ..."
        ocf_run kill -s KILL $pid
    fi

    ocf_log info "OpenStack VPN Server (neutron-vpn-agent) stopped"

    rm -f $OCF_RESKEY_pid

    return $OCF_SUCCESS
}

#######################################################################

case "$1" in
  meta-data)    meta_data
                exit $OCF_SUCCESS;;
  usage|help)   usage
                exit $OCF_SUCCESS;;
esac

# Anything except meta-data and help must pass validation
neutron_vpn_agent_validate || exit $?

# What kind of method was invoked?
case "$1" in
  start)        neutron_vpn_agent_start;;
  stop)         neutron_vpn_agent_stop;;
  status)       neutron_vpn_agent_status;;
  monitor)      neutron_vpn_agent_monitor;;
  validate-all) ;;
  *)            usage
                exit $OCF_ERR_UNIMPLEMENTED;;
esac
